version: '3'

services:
  db:
    image: mysql:8.0
    hostname: db_mysql
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - fedcommon

  idp-1-hospital-1:
    build:
      context: .
      dockerfile: ./idp-1/hospital-1/Dockerfile
    hostname: hospital1
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - fedcommon

  idp-1-hospital-2:
    build:
      context: .
      dockerfile: ./idp-1/hospital-2/Dockerfile
    hostname: hospital2
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - fedcommon

  fed:
    build:
      context: .
      dockerfile: ./fed/Dockerfile
    hostname: fed
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - fedcommon

  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    restart: always
    depends_on:
      - idp-1-hospital-1
      - idp-1-hospital-2
      - db
    networks:
      - fedcommon

networks:
  fedcommon:
    external: true

